.circleci/config.yml, .gitignore, config/blacklight.yml
Connected to https://github.com/emory-libraries/dlp-lux/issues/22
=> Set up CircleCI and Coveralls

architecture-decisions/0000-TEMPLATE.md, architecture-decisions/0001-document-architecture-decisions.md
Also adds a template for future ADRs.
=> Adds ADRs and accepts that decision

config/deploy.rb
The branch will remove all references to dlp-lux-temp.
=> Remove references to dlp-lux-temp

config/deploy.rb, config/deploy/dce-localhost.rb, config/deploy/qa.rb
Connected to https://github.com/emory-libraries/dlp-lux/issues/33
=> Deploy to dce aws

.circleci/config.yml
When a system test fails, capybara will take a screenshot of the failure. When this happens in Circle, this PR uploads them as artifacts.
=> Captures screenshots for system test failures on Circle

Gemfile, Gemfile.lock, README.md
The README is updated with instructions for setting up MySQL databases for local development and testing. The sqlite gem is also removed from the Gemfile because it is no longer being used.
=> Document MySQL configuration

app/controllers/catalog_controller.rb, spec/system/view_search_results_spec.rb
Add creator, date created, content_type uri to search results
=> Add index fields to search results

Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/controllers/catalog_controller.rb, app/views/catalog/_index.html.erb
Correctly nests thumbnails and metadata.
Still need to make labels not-bold and right-aligned.
=> Thumbnails in search results

app/assets/javascripts/uv_width.js, app/assets/stylesheets/uv.css, app/views/catalog/_uv.html.erb, config/uv/uv.html
* Does not hide the title
* Removes duplicated zoom controls
* Adds fullscreen button
* Uses a larged fixed width to trigger the desktop UI
* Adds a small script to resize UV based on the width of the page
=> Initial UV config changes

app/controllers/catalog_controller.rb, app/views/catalog/_index.html.erb, spec/system/view_search_results_spec.rb
=> Search results metadata - formatting and human readable content_type

app/views/catalog/_about_this_item.html.erb, app/views/catalog/_access_and_copyright.html.erb, app/views/catalog/_contains.html.erb, app/views/catalog/_find_this_item.html.erb, app/views/catalog/_is_part_of.html.erb, app/views/catalog/_metadata_groupings.html.erb, app/views/catalog/_misc_details.html.erb, app/views/catalog/_publication_details.html.erb, app/views/catalog/_related_material.html.erb, app/views/catalog/_show.html.erb, app/views/catalog/_subjects_keywords.html.erb, app/views/catalog/show.html.erb, config/initializers/layout_helper_behavior.rb, spec/system/view_work_spec.rb
* Create partials for show page
* Initial partial layout
=> Create partials for metadata show page

app/controllers/catalog_controller.rb, app/presenters/access_and_copyright_presenter.rb, app/views/catalog/_access_and_copyright.html.erb, config/metadata/access_and_copyright.yml, spec/presenters/copyright_and_access_presenter_spec.rb, spec/support/solr_documents/curate_generic_work.rb, spec/system/view_work_spec.rb
=> Change names to match header, add human readable fields

app/controllers/catalog_controller.rb, app/presenters/is_part_of_presenter.rb, app/views/catalog/_is_part_of.html.erb, app/views/catalog/_metadata_groupings.html.erb, app/views/catalog/_relationship_block.html.erb, config/metadata/is_part_of.yml, spec/presenters/contains_presenter_spec.rb, spec/presenters/is_part_of_presenter_spec.rb, spec/support/solr_documents/curate_generic_work.rb, spec/system/view_work_spec.rb
=> "This item is part of" presentation, start "Contains"

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/support/solr_helpers.rb, spec/system/search_catalog_spec.rb, spec/system/view_search_results_spec.rb
Connected to: https://github.com/emory-libraries/dlp-lux/issues/121
=> Configure default search fields

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/controllers/omniauth_callbacks_controller.rb, app/controllers/omniauth_controller.rb, app/models/auth_config.rb, app/models/user.rb, app/views/devise/sessions/new.html.erb, config/initializers/devise.rb, config/routes.rb, db/migrate/20191218155952_add_omniauth_to_users.rb, db/migrate/20191218163721_add_display_name_to_users.rb, db/schema.rb, spec/models/user_spec.rb
This adds shibboleth to the app based on
the instructions here:
https://curationexperts.github.io/playbook/authentication/shibboleth_and_hyrax.html
=> Add Shibboleth setup

db/migrate/20191218172833_remove_email_index_from_users.rb, db/migrate/20191218172908_allow_null_email_in_users.rb, db/schema.rb
See https://github.com/curationexperts/laevigata/commit/5c3c4a7d9a67dad545ff694e6bbad3b146e850af
=> Additional shibboleth db setup

Gemfile, Gemfile.lock, app/models/user.rb, app/views/_user_util_links.html.erb, app/views/shared/_user_util_links.html.erb, config/routes.rb, spec/models/user_spec.rb
* Removes automatic guest creation
* Changes views to reflect our User model
* Adds PPID to the user (right now this is not being returned by shib)
* Removes trackable from the OmniAuth user (we are not tracking IPs and sign-ins)
* Updates routes to reflect what shibboleth expects
* Updates specs to match what we are getting from Emory's shib
=> Add additional Emory config for shibboleth

app/views/catalog/_is_part_of.html.erb
=> Add Google Analytics code for holding_repository

Gemfile, app/views/advanced/_advanced_search_facets.html.erb, spec/factories/users.rb, spec/rails_helper.rb, spec/system/user_nav_bar_spec.rb
* Add factorybot for user authentication testing
* Organize gemfile
* Pull over advanced search facets partial to get rid of deprecation warning
=> Authentication test

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.css, app/controllers/catalog_controller.rb, app/models/search_builder.rb, config/routes.rb, spec/system/facet_by_year_spec.rb
- `blacklight_range_limit` gem is installed to allow year ranges for date facet
- The slider supports year 1000 to the current year
=> Use date slider for date facet

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/system/advanced_search_spec.rb
Search fields on the advanced search page are decoupled per #224
=> Customize advanced search fields

app/views/advanced/_advanced_search_help.html.erb
- Search tips on the advanced search page are edited to reflect the behavior of advanced search
=> Revise search tips

.rubocop.yml, lib/blacklight/access_controls/ability.rb, spec/system/visibility_spec.rb
* Both authenticated and unauthenticated users can see Public Low Resolution show pages
* Only authenticated users can see Emory Low Resolution show pages, unauthenticated users cannot
Public low - logged out
Public low - logged in
Emory low - logged out
Emory low - logged in
=> Public low resolution and Emory low resolution displays correct page

app/controllers/catalog_controller.rb
- Sort label for date updated per comment on #245
=> Change sort label to date

app/controllers/application_controller.rb, spec/requests/uv_config_spec.rb, spec/system/visibility_spec.rb
Public - not logged in
Public - logged in 
Public Low View - not logged in
Public Low View - logged in
Emory Low View - logged in
Can't find an example work that has working IIIF and
=> UV config depends on both user authentication and object visibility

.circleci/config.yml, README.md, app/controllers/application_controller.rb, dotenv.sample, lib/blacklight/access_controls/ability.rb, spec/requests/visibility_request_spec.rb
Logged out, from the "right" IP
Logged in, from the "right" IP
Logged out, from the "wrong" IP
Logged in, from the "wrong" IP
=> Only people in the Rose Reading Room should be able to see "Rose High View" objects in Lux

app/controllers/catalog_controller.rb, spec/system/sort_results_spec.rb
Can select both ascending and descending versions of each sort.
=> Sort both ascending and descending

app/views/catalog/_this_item_contains_block.html.erb
- Remove errant percent sign preventing images from displaying properly
=> Correct source for child work images

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/requests/uv_config_spec.rb, spec/requests/visibility_request_spec.rb, spec/support/capybara.rb, spec/support/solr_documents/visibility_curate_generic_works.rb, spec/system/facet_by_visibility_spec.rb, spec/system/search_catalog_spec.rb, spec/system/search_results_visibility_spec.rb, spec/system/show_page_visibility_spec.rb
Re-factor visibility specs with fixture objects
=> Visibility pivot facet

app/controllers/catalog_controller.rb, public/404.html, spec/controllers/catalog_controller_spec.rb, spec/system/show_page_visibility_spec.rb
=> Visibility Facet & Update 404

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/support/solr_documents/curate_generic_work.rb, spec/support/solr_documents/curate_generic_work_child.rb
- Restore changes to Access index field from #338
=> Revert changes to Access index field

app/assets/stylesheets/lux/_colors.scss
- Bring in colors from Emory Libraries Pattern Library
=> Change color definitions

app/assets/stylesheets/application.css, app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/lux.scss, app/assets/stylesheets/lux/_cards.scss, app/assets/stylesheets/lux/_colors.scss, app/assets/stylesheets/lux/_fonts.scss, app/assets/stylesheets/lux/_navbar.scss, app/assets/stylesheets/lux/_variables.scss, app/views/blacklight/nav/_bookmark.html.erb, app/views/blacklight/nav/_search_history.html.erb, app/views/catalog/_facet_group.html.erb, app/views/catalog/_search_form.html.erb, app/views/catalog/_search_results.html.erb, app/views/catalog/_show_tools.html.erb, app/views/layouts/application.html.erb, app/views/layouts/blacklight/base.html.erb, app/views/nav/_advanced_search.html.erb, app/views/shared/_big_nav.html.erb, app/views/shared/_header_navbar.html.erb, app/views/shared/_top_links.html.erb, app/views/shared/_user_util_links.html.erb, config/locales/blacklight.en.yml
Refactor styles, trying to limit custom CSS as much as possible
=> Bootstrap refactor

app/assets/stylesheets/lux/_navbar.scss, app/assets/stylesheets/lux/_search_form.scss, app/assets/stylesheets/lux/_variables.scss, app/views/shared/_big_nav.html.erb, app/views/shared/_header_navbar.html.erb
Small fixes to header, caps, letter spacing
=> Top nav Emory branding, remove unneeded spacer

spec/spec_helper.rb, spec/system/footer_spec.rb
=> Remove test with external dependencies

app/controllers/application_controller.rb, app/controllers/static_controller.rb, app/views/shared/_footer_list.html.erb, app/views/shared/_top_links.html.erb, app/views/static/_content_chunk.html.erb, app/views/static/about.html.erb, config/routes.rb, spec/requests/about_digital_collections_spec.rb, spec/system/footer_spec.rb
Fulfills the content requirements for a ticket # 352, minus detailed styling which I was advised to leave out.
=> About digital collections 352

app/controllers/static_controller.rb, app/views/shared/_footer_list.html.erb, app/views/static/copyright_reuse.html.erb, config/routes.rb, spec/requests/copyright_reuse_spec.rb, spec/system/footer_spec.rb
1. static_controller.rb: adds the action to this controller.
2. _footer_list.html.erb: changes the path to this new page away from root.
3. copyright_reuse.html.erb: inserts the view.
4. routes.rb: draws a path for this view to the action.
5. copyright_reuse_spec.rb: writes and instigates the tests for this view.
6. footer_spec.rb: corrects the path the test for this view should be looking for.
=> Creates the Copyright and Reuse page.

app/presenters/blacklight/thumbnail_presenter.rb, spec/support/solr_documents/visibility_curate_generic_works.rb, spec/system/search_results_visibility_spec.rb
=> Thumbs log in only

app/assets/stylesheets/lux/_navbar.scss
Addresses feedback about header's max-width
=> Adjust width of application header

app/views/catalog/_is_part_of_block.html.erb, spec/system/view_multi_part_work_spec.rb
1. view_multi_part_work_spec.rb: creates tests to see if link is populates.
2. _is_part_of_block.html.erb: adds logic and link to partial.
=> Adds a link to parent work when viewing child work.

app/assets/stylesheets/lux/_facets.scss, app/assets/stylesheets/lux/_variables.scss, app/controllers/catalog_controller.rb, spec/system/faceted_search_spec.rb
- Facet label for "Subject - Geographic Locations" is shortened to unify the size of all facets
- Font size, line height, and padding on facet values is reduced for better readability
=> Fine-tune display of facets

app/assets/stylesheets/lux.scss, app/assets/stylesheets/lux/_cards.scss, app/assets/stylesheets/lux/_show_button.scss, app/assets/stylesheets/lux/_show_heading.scss, app/assets/stylesheets/lux/_variables.scss, app/views/catalog/_about_this_collection_block.html.erb, app/views/catalog/_about_this_item.html.erb, app/views/catalog/_access_and_copyright_block.html.erb, app/views/catalog/_additional_details.html.erb, app/views/catalog/_find_this_item.html.erb, app/views/catalog/_is_part_of_block.html.erb, app/views/catalog/_metadata_block.html.erb, app/views/catalog/_publication_details.html.erb, app/views/catalog/_related_material.html.erb, app/views/catalog/_show_header.html.erb, app/views/catalog/_show_tools.html.erb, app/views/catalog/_subjects_keywords.html.erb, app/views/catalog/_this_item_contains_block.html.erb, app/views/catalog/_view_items_in_collection_block.html.erb, app/views/catalog/show.html.erb
1. lux.scss: adds two new partials to the main style page.
2. _cards.scss: changes border radius to 0 and adds size to font.
3. _show_button.scss: refines styling for the buttons on main show block.
4. _show_heading.scss: corrects the font styling on show header.
5. show.html.erb: changes classes away from bootstrap standard to EUL standard.
=> Styles the show/work page.

app/assets/stylesheets/lux/_variables.scss
- Removes rules that inadvertently reduced the font size and font weight of facet headings
=> Fix facet font sizes

app/assets/stylesheets/lux.scss, app/assets/stylesheets/lux/_breadcrumbs.scss, app/assets/stylesheets/lux/_collection_image.scss, app/assets/stylesheets/lux/_show_button.scss, app/assets/stylesheets/lux/_variables.scss, app/views/catalog/_breadcrumbs.html.erb
1. lux.scss: adds the collection_image partial.
2. _breadcrumbs.scss: adds margin to the top of the margin
3. _collection_image.scss: inserts margin space to the bottom of
the collection banner.
4. _show_button.scss: matches the text spacing (top/bottom) of the
search button.
5. _variables.scss: creates a variable for the line-height value used
in show_button partial.
6. _breadcrumbs.html.erb: adds class to the breadcrumbs container.
=> Styles the collection page.

README.md, jmeter/blacklight.jmx, jmeter/user.properties
Include jmeter test plan to test blacklight performance.
=> Blacklight performance

app/assets/stylesheets/lux.scss, app/assets/stylesheets/lux/_colors.scss, app/assets/stylesheets/lux/_static_body.scss, app/assets/stylesheets/lux/_static_headers.scss, app/assets/stylesheets/lux/_variables.scss, app/views/static/_static_content_blurbs.html.erb, app/views/static/_static_heading.html.erb, app/views/static/about.html.erb, config/locales/en.yml, spec/requests/about_digital_collections_spec.rb
1. app/assets/stylesheets/*: adds new styling to new content.
2. _static_content_blurbs.html.erb and _static_heading.html.erb: creates new
partials to address the differing structure of the new content.
3. about.html.erb: revises view with new content.
4. en.yml: adds new translation to use.
5. about_digital_collections_spec.rb: has new tests to look for additional material.
=> Updates verbiage in the /about view.

app/assets/stylesheets/lux/_static_body.scss, app/views/static/about.html.erb, app/views/static/contact.html.erb, config/locales/en.yml, spec/requests/contact_spec.rb, spec/system/breadcrumb_links_spec.rb
- Updates contact page with correct content and styles
- Revises breakpoints on all static pages
- Updates links on all static pages to match Emory pattern library links
=> Update contact page

app/assets/stylesheets/lux.scss, app/assets/stylesheets/lux/_bookmark_clear_button.scss, app/assets/stylesheets/lux/_bookmarks_header.scss, app/assets/stylesheets/lux/_bookmarks_nav.scss, app/views/bookmarks/_clear_bookmarks_widget.html.erb, app/views/bookmarks/index.html.erb, app/views/catalog/_sort_and_per_page.html.erb
1. lux.scss: adds the new scss partial.
2. _bookmark_clear_button.scss: creates partial that contains all css for this page.
3. _clear_bookmarks_widget.html.erb and index.html.erb: brings in blacklight default to adjust the displayed styling.
4. _bookmarks_header.scss: styles the area surrounding the heading.
5. _sort_and_per_page.html.erb: changes bootstrap column settings.
=> Styles the Bookmarks index page.

app/assets/stylesheets/lux.scss, app/assets/stylesheets/lux/_search_history.scss, app/assets/stylesheets/lux/_static_headers.scss, app/views/search_history/index.html.erb
- Applies correct font and button styles to search history page
=> Style search history page

app/assets/stylesheets/lux/_navbar.scss, app/controllers/catalog_controller.rb, app/views/catalog/_feedback_link.html.erb, app/views/catalog/_help_link.html.erb, spec/system/view_collection_spec.rb, spec/system/view_work_spec.rb
1. app/assets/stylesheets*: implements requested padding adjustment.
2. app/controllers/catalog_controller.rb: comments out the links wanted removed and adds the anchors asked for.
3. app/views/catalog/*: creates partials to hold the links.
4. spec/system/*: inserts testing to see if links populate.
=> Edits and adds new links to Tools section.

app/views/shared/_footer_list.html.erb, spec/system/footer_spec.rb
1. _footer_list.html.erb: swaps out links and text.
2. footer_spec.rb: changes tests expectations.
=> Updates links and verbiage of footer.

app/assets/javascripts/hero_image.js
- Ensures that the JavaScript running the image carousel is called after following Turbolinks within Lux
=> Retrigger image carousel after clicking internal links

app/assets/stylesheets/lux/_advanced_search.scss, app/assets/stylesheets/lux/_footer_branding_dropdown.scss, app/assets/stylesheets/lux/_search_form.scss
=> alternate way to show chevrons locally

app/controllers/catalog_controller.rb, spec/system/view_collection_spec.rb, spec/system/view_work_spec.rb
Reverts emory-libraries/dlp-lux#547
=> Revert "Remove cite link"

app/views/static/about.html.erb
1. about.html.erb: changes the text as per the wireframe in #566 ticket.
=> Updates the verbiage on the about page.

app/assets/stylesheets/lux/_footer.scss, app/assets/stylesheets/lux/_variables.scss
1. _footer.scss: adds new rule for footer height and replaces pixel amounts with rem variables.
2. _variables.scss: creates new variables for measurements pertaining to the footer.
=> Adjusts the maximum footer height (Non-mobile sizes).

app/assets/stylesheets/lux/_facets.scss
1. _facets.scss: adds css rule for header tag.
=> Changes font color of the Facets Header.

app/helpers/additional_catalog_helper.rb, app/views/catalog/_find_this_item_block.html.erb
1. Uses the value pulling logic in a new method defined to just handle the persisted URL on this page.
=> DRYs up the find this item partial.

app/assets/stylesheets/lux/_breadcrumbs.scss, app/assets/stylesheets/lux/_constraints.scss, app/assets/stylesheets/lux/_navbar.scss, app/assets/stylesheets/lux/_sort_widgets.scss, app/assets/stylesheets/lux/_variables.scss, app/views/shared/_header_navbar.html.erb
1. app/assets/stylesheets/lux/*: alters top and bottom margins of the listed elements.
2. _header_navbar.html.erb: inserts descriptive class for easier styling.
=> Adjusts the margin between show page top elements #580.

app/assets/stylesheets/lux/_collection_image.scss, app/assets/stylesheets/lux/_variables.scss
1. _collection_image.scss: swaps out old spacer for new variable.
2. _variables.scss: creates new variable for hero image bottom margin.
=> Adds bottom margin to the collection hero image.

app/assets/stylesheets/lux/_static_body.scss, app/assets/stylesheets/lux/_variables.scss
1. _static_body.scss: inserts the margin into the top of the card.
2. _variables.scss: institutes a variable for the needed margin value.
=> Adds top margin to the explore collection cards #585.

app/assets/stylesheets/lux/_show_heading.scss, app/assets/stylesheets/lux/_static_headers.scss, app/assets/stylesheets/lux/_variables.scss
1. _show_heading.scss and _static_headers.scss: inserts line height css into selectors.
2. _variables.scss: creates new variable for h1 line height.
=> Changes line height throughout the application.

app/assets/stylesheets/lux/_hero_image.scss, app/views/catalog/_hero_image.html.erb
=> Adds text overlay to hero image carousel

app/views/shared/_big_nav.html.erb, spec/system/header_spec.rb
- app/views/shared/_big_nav.html.erb: changes destination of two links.
- spec/system/header_spec.rb: adds new tests and cleans up structure.
=> Corrects the links on the header (#633).

app/assets/stylesheets/lux/_breadcrumbs.scss, app/assets/stylesheets/lux/_colors.scss
- app/assets/stylesheets/lux/_breadcrumbs.scss: switches colors to one of our standardized choices.
- app/assets/stylesheets/lux/_colors.scss: removes specialized color.
=> Swaps out breadcrumb colors (#652).

app/views/catalog/_uv.html.erb
=> Add title to UV iframe

app/controllers/omniauth_callbacks_controller.rb, app/controllers/omniauth_controller.rb, spec/controllers/omniauth_callbacks_controller_spec.rb
- app/controllers/omniauth_callbacks_controller.rb: provides three options to redirect to, starting with the newly created `session[:requested_page]`.
- app/controllers/omniauth_controller.rb: inserts the needed session variable.
- spec/controllers/omniauth_callbacks_controller_spec.rb: changes the expectations for the redirect processing.
=> Creates session variable that holds the page that the user requested (#191).

app/views/static/about.html.erb, spec/requests/about_digital_collections_spec.rb
=> Add accessibility statement to about page

app/models/solr_document.rb, app/views/catalog/_is_part_of_block.html.erb, spec/system/view_work_spec.rb
* We are adding source collection to work show page breadcrumb and to the is part of block.
Connected to: #680
=> Adds source collection links to work show page

app/views/catalog/_is_part_of_block.html.erb
app/views/catalog/_is_part_of_block.html.erb: replaces `member_of_collections_ssim` with `source_collection_title_ssim` field value.
=> Points the collection views event to Source Collection Title (#696).

app/views/catalog/_facet_group.html.erb, app/views/catalog/_is_part_of_block.html.erb
=> Add tracking for facet events

app/assets/stylesheets/lux/_navbar.scss, app/assets/stylesheets/lux/_search_form.scss
=> Makes the searchbar visible in iPhone widths (#725).
