emory-libraries/dlp-lux

.circleci/config.yml
config/database.yml

As a consequence, we can no longer use the Samvera Orb's executor. This also means no more Fedora.

Adds and configures MySQL for CircleCI

---

app/controllers/catalog_controller.rb

This removes the default fields from the blacklight
catalog controller because our application will
not have these fields in solr. Examples are
left commented out for future reference.
Connected to #62

Remove Blacklight catalog defaults

---

README.md
config/initializers/iiif_url.rb
dotenv.sample

This includes a dotenv sample file with
vars that are used in the database config
file and an example for the IIIF url.
The README is also updates to include info
about needing to set the IIIF url.
Connected to #61

Add a sample dotenv file

---

config/deploy/arch.rb
config/deploy/production.rb
config/deploy/test.rb

This allows us to not only differentiate between Curate and Lux, but the different deployment envs for each.

Reports different environments to Honeybadger

---

app/controllers/catalog_controller.rb
app/views/catalog/_show.html.erb
spec/system/view_search_results_spec.rb
spec/system/view_work_spec.rb

"About this item" and "Keywords" (see https://docs.google.com/spreadsheets/d/1bODcf-cLwBNOv7UDtNE39M1OoRW93o6xRVDZMGX-eaQ/edit#gid=696928716) sections of metadata added to Show page. (image 1)
Also did first pass at adding facets to verify Solr index. While they look good at first glance, the Curate-created Solr index will need to be updated for many of the faceted fields to appear correctly (e.g. "New Jersey" appears as "new" and "jersey" because of how it is stored in the Solr index)

Metadata added to show page, start facets

---

app/assets/javascripts/uv_width.js
app/helpers/blacklight/layout_helper_behavior.rb
app/views/catalog/_about_this_item.html.erb
app/views/catalog/_access_and_copyright.html.erb
app/views/catalog/_find_this_item.html.erb
app/views/catalog/_index.html.erb
app/views/catalog/_metadata_block.html.erb
app/views/catalog/_metadata_groupings.html.erb
app/views/catalog/_misc_details.html.erb
app/views/catalog/_publication_details.html.erb
app/views/catalog/_related_material.html.erb
app/views/catalog/_subjects_keywords.html.erb

This alters the partials so that have better
spacing and changes the layout in the grouping
so that the header is on a different row than
the value.
There is a new partial that can be used to output
a metadata block. It can be used like this:
```ruby
<%= render 'metadata_block', document: document, presenter: AccessAndCopyrightPresenter, presenter_class: 'access-and-copyright', title: 'Access and Copyright' %>
```

Update metadata groupings

---

app/views/catalog/_contains.html.erb
app/views/catalog/_metadata_groupings.html.erb
spec/system/view_work_spec.rb

Given the conversation on #154, the "This item contains" section does not apply to a simple object show page, so its corresponding partial is now removed.

Remove partial for This item contains

---

.rubocop.yml
Gemfile
Gemfile.lock
app/assets/stylesheets/application.css
app/controllers/catalog_controller.rb
app/controllers/saved_searches_controller.rb
app/controllers/search_history_controller.rb
app/models/search_builder.rb
app/views/catalog/_search_form.html.erb
config/routes.rb
spec/system/advanced_search_spec.rb

- The `blacklight_advanced_search` gem was added from git because there has not yet been a release compatible with Blacklight 7
- We will reach out to the community to find out why there has not been a recent release
- This PR does not actually add advanced search functionality because the problem seems to stem from an existing problem with drop-down search in Lux, which will be addressed in a future sprint

Add advanced_search gem

---

app/controllers/saved_searches_controller.rb
app/controllers/search_history_controller.rb

These controllers were added by blacklight_advanced_search plugin, but they were causing problems with deploy. We cannot find any requirements for saved searches, so we are removing them.

Remove unneeded controllers

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb
spec/system/search_catalog_spec.rb
spec/system/targeted_field_search_spec.rb

- Fields specified in #125 are added to targeted search
- `catalog_controller_spec.rb` and `search_catalog_spec.rb` are updated to match new search requirements

Configure targeted search fields

---

app/views/advanced/_advanced_search_form.html.erb
spec/system/advanced_search_spec.rb

Facets on the advanced search page exhibit unexpected behavior (see #218). Because there are no known requirements specifying their presence, they are being removed.

Remove facets from advanced search page

---

app/controllers/catalog_controller.rb

If a facet (besides Date and Rights Status) has more than 5 options, those options can be sorted either alphabetically or numerically. The default is numerical sorting.

Allow facet options to be sorted alphabetically

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
app/models/ability.rb
app/models/search_builder.rb
app/models/user.rb
app/views/catalog/_uv.html.erb
config/initializers/blacklight_access_controls.rb
spec/support/solr_documents/collection.rb
spec/support/solr_documents/curate_generic_work.rb
spec/system/view_unauthorized_spec.rb
spec/system/visibility_spec.rb

Currently search results show all Works and Collections, but if user is 
not logged in, restricted items go to 404 page, not show page.
Further work is needed to have search results reflect user's authorization
Logged in
Same page, not logged in

Emory high view

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb

Initial addition of "Access Group" to search results and facets to facilitate testing and continued feedback.

Add access group to search and facets for usability

---

app/controllers/catalog_controller.rb
app/views/advanced/_advanced_search_submit_btns.html.erb
spec/system/sort_results_spec.rb

- The default sort fields (relevance, year, creator, and title) are implemented using sortable fields added to Curate.
- Sorting works both in simple search and on the advanced search page.
- Once deployed, sorting by year should work immediately. Title and creator sorting should work once the respective sortable fields are re-indexed in Curate.

Add default sort behavior

---

Gemfile
Gemfile.lock

Cannot deploy to servers, OpenSSH keys need these additional gems for support.

Gems for OpenSSH key support

---

app/controllers/catalog_controller.rb
spec/system/sort_results_spec.rb

- Sorting objects by date now uses a single-valued `:year_for_lux` field indexed in Curate
- Date sorting will go by an object's earliest year per #277
- See [Curate PR 937](https://github.com/emory-libraries/dlp-curate/pull/937)

Fix sorting by date

---

app/controllers/catalog_controller.rb
app/presenters/this_item_contains_presenter.rb
app/views/catalog/_metadata_col_2.html.erb
app/views/catalog/_this_item_contains.html.erb
app/views/catalog/_this_item_contains_block.html.erb
app/views/catalog/_uv.html.erb
spec/presenters/this_item_contains_presenter_spec.rb

- Hierarchical works (i.e., CurateGenericWorks that have CurateGenericWorks as children) now display their child works in a partial on the show page
- The show page for hierarchical works suppresses the Universal Viewer

Update hierarchical work show page

---

app/values/uv_configuration.rb
spec/values/uv_configuration_spec.rb

* We are removing `About the item` text that appears in the more info tab.
Before:
After:
Connected to emory-libraries/dlp-curate#988

Removes 'About the item' tab from more info tab

---

app/assets/stylesheets/lux/_search_form.scss
app/assets/stylesheets/lux/_variables.scss
app/views/catalog/_search_form.html.erb
app/views/shared/_big_nav.html.erb

Search box takes up greater proportion of navigation, align right, make drop-down text full size until small sizes, text entry box takes up most of real estate as element gets smaller.

Search box styling

---

app/assets/stylesheets/lux.scss
app/assets/stylesheets/lux/_footer_copyright.scss
app/assets/stylesheets/lux/_footer_placeholder.scss
app/views/shared/_footer.html.erb

- Dividers now appear before the address and the phone number in the footer at the specified breakpoint
- A placeholder div is added to the footer where the social media links would have been in order to bring the footer to the specified height in pixels

Fix footer dividers and height

---

app/views/shared/_big_nav.html.erb
spec/system/search_catalog_spec.rb

1. _big_nav.html.erb: form action in search form partial wasn't working correctly
due to big nav partial wrapping that partial in another form tag. Rails got confused
and cancelled out the second form tag's action.

Fixes the search issue by removing redundant tag.

---

app/controllers/application_controller.rb
spec/requests/visibility_request_spec.rb

Per Emory middleware, need to include X-Forwarded-For headers to capture user's IP address for "Rose High View" IP restrictions, rather than the Load Balancer's IP address.

X forwarded for

---

README.md
app/controllers/application_controller.rb
app/controllers/concerns/http_auth_concern.rb
spec/system/password_protect_spec.rb

This will let us set up http password protection via environment variables, so it can easily be switched on and off.
Set `HTTP_PASSWORD_PROTECT='true'` in `.env.production` to enable password protection.
Login and password values are set via `HTTP_USERNAME` and `HTTP_PASSWORD`

Use http password protection to prevent crawling

---

app/views/catalog/_show.html.erb
spec/system/view_collection_spec.rb

1. _show.html.erb: broadens the logic of what is seen when
document is a Collection and banner path is passed through.
Also creates an image tag with unique id.
2. view_collection_spec.rb: inserts tests for banner delivery.

Adds the branding banner that is set in curate to the collection show page when it exists.

---

app/controllers/application_controller.rb
spec/requests/uv_config_spec.rb

* Emory Low Download works have a download specification that makes sure the height of the image being downloaded is always restricted to 400px. In this commit, we change the options (text) that show up in the download dialogue so we can see only one option which is whole image limited to 400px.
Before:
After:
* Download options:
* `currentViewDisabledPercentage` is set to 0, because the width and the height of the actual image will always be greater, and this will hide the current view download button (refer: https://github.com/UniversalViewer/universalviewer/blob/2a08b8aa87dce7dd5d4d6c65c63df495bebe9775/src/extensions/uv-seadragon-extension/DownloadDialogue.ts#L383)
* `confinedImageSize` is set to a high width because the Whole Image Low Res option will be hidden as long as the width of …

Edits download options text for emory_low_download works

---

app/assets/stylesheets/lux.scss
app/assets/stylesheets/lux/_buttons.scss
app/assets/stylesheets/lux/_cards.scss
app/assets/stylesheets/lux/_colors.scss
app/assets/stylesheets/lux/_facets.scss
app/assets/stylesheets/lux/_search_form.scss
app/assets/stylesheets/lux/_variables.scss
config/locales/blacklight.en.yml

- Default Blacklight styles are selectively brought in and adapted for Lux facets
- Lux's default green is changed to Blacklight's default green in order to have acceptable color contrast on active facet elements
- Generic button rules from `_variables.scss` are removed and applied more selectively to the search form button
- Generic card rules from `_variables.scss` and `_buttons.scss` are removed and applied more selectively to cards on the show page so as not to override the facet styling

Style facets

---

config/explore_collections.yml

- Because the IDs of these objects are different in each environment, each link is hard-coded for production

Explore collections fix

---

app/assets/stylesheets/lux.scss
app/assets/stylesheets/lux/_advanced_search.scss
app/assets/stylesheets/lux/_variables.scss
app/controllers/catalog_controller.rb
app/views/advanced/_advanced_search_fields.html.erb
app/views/advanced/_advanced_search_submit_btns.html.erb
app/views/advanced/index.html.erb
app/views/catalog/_facet_group.html.erb

- Brings in Emory pattern library styles to advanced search page
- Adds Bootstrap utility classes to default views in advanced search gem
- Unifies capitalization of sort fields
- Fixes bug where facets heading had incorrect font size

Style advanced search page

---

app/assets/stylesheets/lux.scss
app/assets/stylesheets/lux/_copyright_card.scss
app/views/catalog/_access_and_copyright_block.html.erb
spec/system/view_work_spec.rb

1. app/assets/stylesheets/*: creates styling for the text.
2. _access_and_copyright_block.html.erb: injects text into card structure.
3. view_work_spec.rb: uses test to check for text.

Inserts and styles disclaimer in copyright card.

---

app/controllers/omniauth_callbacks_controller.rb
spec/requests/omniauth_callbacks_requests_spec.rb

Use expiration date as cookie value, to make sure cookie values change and are even harder to spoof.

Cookie reboot

---

config/routes.rb
spec/requests/purl_redirection_spec.rb

The redirect uses status 303: 'Found', because we don't want to suggest the object has moved.

Redirect PURLs to the catalog

---

app/assets/stylesheets/lux/_bookmarks_nav.scss
app/views/bookmarks/_tools.html.erb

- Removes Help and Feedback links from Bookmarks page
- Removes errant gray pipe on top right of Bookmarks page

Remove unneeded links on Bookmarks page

---

app/views/catalog/_hero_image.html.erb

- Hero image rotation interval should now be 6 seconds, per product owner

Reduce image carousel rotation interval

---

app/views/blacklight_range_limit/_range_limit_panel.html.erb
spec/system/facet_by_year_spec.rb

- Previously, applying the date slider to an otherwise empty search caused the application to remain on the home page. Now the date slider will apply an empty dummy search field in order for a search to actually be performed.

Show results when only date facet selected

---

app/controllers/catalog_controller.rb
app/presenters/find_this_item_presenter.rb
app/views/catalog/_find_this_item.html.erb
app/views/catalog/_find_this_item_block.html.erb
config/metadata/find_this_item.yml
spec/presenters/find_this_item_presenter_spec.rb
spec/system/view_work_spec.rb

1. catalog_controller.rb: ensures that the "id" key/value gets populated in view.
2. _find_this_item.html.erb: changes render call to the new custom partial listed below.
3. find_this_item.yml: includes id and it's label in fields for the presenter to digest.
4. _find_this_item_block.html.erb: copies from metadata block but adds logic that formats the PURL correctly.
5. spec*: adds test elements for the new metadata link.

Adds Persistent URL link to both Collection and Work views. #540

---

Gemfile
Gemfile.lock
app/assets/stylesheets/lux.scss
app/assets/stylesheets/lux/_citations.scss
app/helpers/citation_helper.rb
app/views/catalog/_citation.html.erb
config/application.rb
config/locales/blacklight.en.yml
lib/emory/citation_formatter.rb
lib/emory/citation_string_processor.rb
spec/lib/citation_formatter_spec.rb
spec/system/work_citation_spec.rb

1. Gemfile*: adds citeproc-ruby and csl-styles gems.
2. app/assets/stylesheets/*: styles the page to Bookmark page's standard.
3. citation_helper.rb: brings the methods defined in the formatter into the views.
4. _citation.html.erb: overrides the blacklight standard template with new helper method calls and redirected translation locations.
5. blacklight.en.yml: initiates new header translations for the citation modal.
6. citation_formatter.rb: fleshes out the logic and return methods to properly format default and CiteProc generated citations.
7. spec/*: formulates testing for both the formatter and the view.

Creates the appropriately styled and formatted citation modal. #490

---

app/assets/stylesheets/lux/_navbar.scss
app/views/shared/_big_nav.html.erb
app/views/shared/_header_navbar.html.erb
app/views/shared/_static_links.html.erb
app/views/shared/_top_links.html.erb
spec/system/advanced_search_spec.rb

1. _navbar.scss: adds styling to hide and show different lists when resized.
2. _big_nav.html.erb: inserts the collapsible links below the button.
3. _header_navbar.html.erb: utilizes newly created partial for static links and classes that assist in hiding top list.
4. _static_links.html.erb: throws often used links into a partial.
5. _top_links.html.erb: creates a partial that encapsulates the two sets of links into a collapsible bootstrap element.
6. advanced_search_spec.rb: points to first link of Advanced Search, since Capybara can only ignore tags that have an inline style of "display:none"

Brings list of links from above Emory logo to under it.

---

app/assets/stylesheets/lux/_results_list.scss
app/views/catalog/_index_header.html.erb
spec/system/sort_results_spec.rb

1. _results_list.scss: realigns the header of each result as two columns that only collapse in mobile view.
2. _index_header.html.erb: groups the result header into a row div and the numbers and links into column divs.
3. sort_results_spec.rb: refactors the expectations of each test since the numbers and links are now separate elements.

Aligns Search Results numbers and headers as separate columns #573.

---

app/assets/stylesheets/lux/_facets.scss

1. _facets.scss: removes the extension of bootstraps standard facet colors.

Swaps out green for our base blue on active facets #574.

---

app/assets/stylesheets/lux/_facets.scss
app/assets/stylesheets/lux/_sort_widgets.scss
app/assets/stylesheets/lux/_variables.scss
app/views/catalog/_facet_group.html.erb
app/views/catalog/_sort_and_per_page.html.erb

1. _facets.scss: adds rule to position toggler closer to the header.
2. _sort_widgets.scss: provides appropriate spacing and location for the 2 buttons.
3. _variables.scss: assigns rem values to variables.
4. _facet_group.html.erb: inserts id to reference in scss.
5. _sort_and_per_page.html.erb: changes column breakpoints.

Optimizes mobile view alignment for pagination and facet toggler #578.

---

app/assets/stylesheets/lux/_show_heading.scss

1. _show_heading.scss: chaqnges text alignment to left.

Aligns document's title to the left #584.

---

app/assets/stylesheets/lux/_variables.scss

1. _variables.scss: cuts the amount of top margin to 5pxs.

Reduces the top margin of facet container on search results page #576.

---

app/views/catalog/_metadata_col_1.html.erb
spec/system/view_collection_spec.rb

* This commit changes the find item heading on collection show page from `Find This Item` to `Find This Collection`
Collection show page:

Change find item heading

---

app/assets/stylesheets/lux/_static_headers.scss

1. _static_headers.scss: matches the top header font size.

Converts the lower headers of static page to 48px #586.

---

app/helpers/additional_catalog_helper.rb
app/views/catalog/_about_this_collection_block.html.erb
app/views/catalog/_metadata_block.html.erb
spec/helpers/additional_catalog_helper_spec.rb

1. additional_catalog_helper.rb: abstracts away the test and processing for making dates fall on multiple lines.
2. _about_this_collection_block.html.erb and _metadata_block.html.erb: adds a switch to the separate line processor if a date field is detected.
3. additional_catalog_helper_spec.rb: creates a test suite for the helpers used here and previously.

Breaks multiple values in date fields into separate lines #583.

---

lib/emory/citation_string_processor.rb

1. lib/emory/citation_string_processor.rb: adds andand protection to `.any?` to protest against unexpected field values.

Defeats errors caused buy .any? testing on nil.

---

app/helpers/render_constraints_helper.rb
app/views/blacklight_range_limit/_range_limit_panel.html.erb
spec/system/facet_by_year_spec.rb

- render_constraints_helper.rb: initiates override of `query_has_constraints?` to include `:range` and adds two more needed methods.
- _range_limit_panel.html.erb: swaps out link for method call that corrects the unknown limiter's parameters.
- facet_by_year_spec.rb: bolsters the testing for facet_by_year.

Corrects "Unknown" limiter path and constraint logic #611. 

---

config/initializers/devise.rb

* Sometimes even though a user is authenticated through shib, their devise cookie might have expired which leads to the Lux app assuming that the user has logged out, that leads to some broken thumbnails. We are setting the devise user session timeout config to 24 hours to avoid this. After this duration the user will be asked to login again.
In case our solution here doesn't work there is another gem that handles devise session timeouts: https://github.com/pelargir/auto-session-timeout
Connected to #561

Adds timeout duration for devise

---

app/views/layouts/blacklight/base.html.erb
config/locales/blacklight.en.yml
spec/system/front_page_spec.rb

- base.html.erb: inserts the meta tag into the homepage.
- blacklight.en.yml: adds the description into localization.
- front_page_spec.rb: creates a test to check its existence.

Adds description meta tag for better SEO (#621).

---

config/locales/blacklight.en.yml
spec/system/view_search_history_spec.rb

- config/locales/blacklight.en.yml: overrides gem locale translation.
- spec/*: tests for right text.

Changes verbiage on search history page (#627).

---

app/views/static/not_found.html.erb
config/locales/blacklight.en.yml
spec/requests/not_found_spec.rb
spec/system/show_page_visibility_spec.rb
spec/system/view_search_history_spec.rb

- app/views/static/not_found.html.erb: swaps out hardcoded text with localizations. Also removes "Accessing" tutorial.
- config/locales/blacklight.en.yml: defines localization for not found page headers and text.
- spec/* : changes and improves expectations for new verbiage.

Updates the verbiage on the not found page (#550).

---

app/assets/stylesheets/lux/_results_list.scss
app/assets/stylesheets/lux/_variables.scss
app/views/catalog/_index.html.erb
app/views/catalog/_index_header.html.erb

- app/assets/stylesheets/lux/_results_list.scss: alters and adds styling to configure the results page correctly.
- app/assets/stylesheets/lux/_variables.scss: cleans up and adds new variables for search results.
- app/views/catalog/_index.html.erb: inserts bookmark checkbox into the lower row of the result item.
- app/views/catalog/_index_header.html.erb: puts the list number on it's own line and removes the bookmark checkbox from the top header.

Moves search result elements around (#626).

---

app/controllers/catalog_controller.rb
spec/requests/visibility_request_spec.rb
spec/system/search_results_visibility_spec.rb
spec/system/show_page_visibility_spec.rb

- When a non-logged-in user tries to view a work that is login required, they are redirected to the login page

Redirect unauthenticated users to login page

---

app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
spec/requests/visibility_request_spec.rb
spec/system/search_results_visibility_spec.rb
spec/system/show_page_visibility_spec.rb

- When a user tries to access an invalid URL (e.g., the bookmarks page when they are not logged in), they should always go to a 404 page. This PR corrects unintended behavior from #642 .

Always render 404 page for invalid URLs

---

app/assets/stylesheets/lux/_cards.scss
app/views/catalog/_about_this_item_block.html.erb
app/views/catalog/_metadata_block.html.erb
app/views/catalog/_metadata_col_2.html.erb
config/locales/blacklight.en.yml
spec/system/show_page_visibility_spec.rb

- app/assets/stylesheets/lux/_cards.scss: styles the warnings.
- app/views/catalog/_metadata_block.html.erb: inserts logic to fire off warnings.
- config/locales/blacklight.en.yml: makes the text localization calls.
- spec/system/show_page_visibility_spec.rb: tests the delivery of the warnings.

Displays resolution and download warnings based on visibility (#628).

---

app/views/blacklight_range_limit/_range_limit_panel.html.erb

- app/views/blacklight_range_limit/_range_limit_panel.html.erb: this completely strips out the start and end of the range boundaries because the gem itself seems hard coded to only rely on solr's stat attribute from the ajax response, no matter what those arguments are set to.

Removes code declaring date (#554).

---

app/controllers/catalog_controller.rb
app/views/static/reading_room_not_found.html.erb
config/locales/blacklight.en.yml
spec/system/show_page_visibility_spec.rb

- When a user tries to view a reading room only object outside the reading room or a private object, they are taken to a new 404 page with information about those specific access restrictions

Add 404 page for reading room/private works

---

app/assets/stylesheets/lux/_facets.scss
app/views/catalog/_explore_collections.html.erb
app/views/catalog/_facet_group.html.erb
spec/system/front_page_spec.rb

Browse all items when hovered upon:
Link click output:
Will run a blank search
Explore Our Collections when hovered upon:
Link click output:
Will run a search to list all collections in the repo

Embeds additional browse links on homepage

---

app/assets/stylesheets/lux/_hero_image.scss
app/assets/stylesheets/lux/_variables.scss
app/views/catalog/_hero_image.html.erb

- app/assets/stylesheets/lux/_hero_image.scss: expands out the styling of the Hero Image title for a wider array of screen sizes.
- app/assets/stylesheets/lux/_variables.scss: adds a new font size to the variables list.
- app/views/catalog/_hero_image.html.erb: takes away a limiting styling class.

Adjusts y-axis transformation to keep titles front and center (#608).

---

app/models/user.rb

* We are adding the timeoutable module to devise so that it can use the timeout config defined in devise initializer.
Refer: https://github.com/emory-libraries/dlp-lux/blob/master/config/initializers/devise.rb#L176

Adds timeoutable hook to devise

---

app/assets/javascripts/fielded_search_dropdown.js
app/views/catalog/_search_form.html.erb

- Previously, when loading a page from the Turbolinks cache, the script responsible for the fielded search dropdown would be re-triggered and append a duplicate dropdown below the existing one (see [Lux issue 632](https://github.com/emory-libraries/dlp-lux/issues/632)). Now, using the `data-turbolinks-permanent` attribute from the Turbolinks API ([Persisting Elements Across Page Loads](https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads)), the entire search form persists across page loads, whether from a normal render or a cache render.

Make search form scripts compatible with Turbolinks

---

app/assets/stylesheets/lux/_results_list.scss
app/views/catalog/_index_header.html.erb
spec/system/view_search_results_spec.rb

- app/assets/stylesheets/lux/_results_list.scss: points to `dl` instead of `div` and adjusts `dl`'s inherent bottom margin.
- app/views/catalog/_index_header.html.erb: swaps out to `div`.
- spec/system/view_search_results_spec.rb: adds test that checks for `dl` wrapper.

Converts document-heading-second-row into a dl (#655).

---

app/assets/stylesheets/lux/_explore_collections.scss

- The text color of "View Collection" on the homepage collection cards is now accessible (Emory's bright blue #336BE6)

Change color of View Collection

---

app/helpers/about_this_item_helper.rb
app/helpers/find_this_item_helper.rb
app/views/catalog/_about_this_collection_block.html.erb
app/views/catalog/_about_this_item_block.html.erb
app/views/catalog/_access_and_copyright_block.html.erb
app/views/catalog/_find_this_item_block.html.erb
app/views/catalog/_is_part_of_block.html.erb
app/views/catalog/_metadata_block.html.erb
app/views/catalog/_show_tools.html.erb
app/views/catalog/_this_item_contains_block.html.erb
app/views/catalog/_view_items_in_collection_block.html.erb
config/locales/blacklight.en.yml
spec/system/view_work_spec.rb

- app/helpers/*: refactors away some of the logic in the partials.
- _about_this_collection_block.html.erb and _metadata_block.html.erb: adds title element into wrapping `div` and `dl`.
- _about_this_item_block.html.erb and _find_this_item_block.html.erb: ditto above and refactors logic into helper.
- app/views/catalog/_access_and_copyright_block.html.erb: ditto two above, but also adds title to copyright disclaimer.
- app/views/catalog/_is_part_of_block.html.erb: ditto three above and inserts recommended `dt`s that describe the `dd` below. (see https://www.w3.org/TR/WCAG20-TECHS/H40.html)
- _show_tools.html.erb and _this_item_contains_block.html.erb: uses localization for the titles.
- app/views/catalog/_view_items_in_collection_block.html.erb: same as above and inserts a `dt` for …

Improves accessibility with titles reflecting card headers (#656).

---

app/views/catalog/_metadata_all.html.erb
app/views/catalog/_metadata_mobile.html.erb
spec/system/work_citation_spec.rb

- Changes the order and presence of metadata blocks in mobile view
**Sample object in desktop view:**
**Sample object in mobile view with reordered metadata blocks:**

Adjust metadata blocks for mobile

---

app/helpers/blacklight_advanced_search_helper.rb
app/views/advanced/_advanced_search_form.html.erb
spec/support/shared_examples_for_advanced_search.rb
spec/system/advanced_search_spec.rb

- app/helpers/blacklight_advanced_search_helper.rb: rewrites the `select_menu_for_field_operator` helper from `blacklight_advanced_search` to include title attribute.
- app/views/advanced/_advanced_search_form.html.erb: points to new helper. 
- spec/support/shared_examples_for_advanced_search.rb: makes a generic example to process multiple methods in `advanced_search_spec.rb`.
- spec/system/advanced_search_spec.rb: adds a test to check for the title added and refactors the tests to DRY them up.

Inserts title attribute into select element in Advanced Search (#658).

---

app/controllers/catalog_controller.rb
app/controllers/omniauth_controller.rb

- app/controllers/catalog_controller.rb: inserts session variable into catalog controller, where it can be verified locally.
- app/controllers/omniauth_controller.rb: removes the variable here, since it only sees the sign-in url.

Switches variable environment to the catalog controller (#191).

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/explore_collections.js
app/assets/javascripts/fielded_search_dropdown.js
app/assets/javascripts/hero_image.js
app/assets/javascripts/uv_width.js
app/views/catalog/_search_form.html.erb
app/views/catalog/_search_results.html.erb
app/views/layouts/application.html.erb
app/views/layouts/blacklight/base.html.erb

- Gemfile*: removes the Turbolinks Gem.
- app/assets/javascripts/application.js: extracts Turbolinks Javascript.
- uv_width.js and explore_collections.js: changes focus to overall document ready state.
- hero_image.js and fielded_search_dropdown.js: removes unneeded Turbolinks re-triggering.
- _search_form.html.erb, _search_results.html.erb, and base.html.erb: omits calls to turbolink controls.
- app/views/layouts/application.html.erb: takes out the requirement of TL JS and CSS.

Header breaks when pressing back from Advanced Search page (#673).

---

app/controllers/catalog_controller.rb
spec/controllers/catalog_controller_spec.rb
spec/system/faceted_search_spec.rb

- app/controllers/catalog_controller.rb: swaps from `member_of_collections_ssim` to `source_collection_title_ssim`.
- spec/*: changes expectations to new field.

Swaps Collection facet to source_collection_title field (#684).

---

app/views/catalog/_facet_pagination.html.erb
app/views/catalog/facet.html.erb

- app/views/catalog/_facet_pagination.html.erb: swaps out plain html span call to a content_tag erb helper used in later versions of Blacklight.
- app/views/catalog/facet.html.erb: alters the layout of the bottom rendering of the facet pagination bar so that it aligns the same as the top.

Omits the </span> tag that shows in facet modal pagination (#685).

---

app/views/catalog/_explore_collections.html.erb
spec/system/front_page_spec.rb

- app/views/catalog/_explore_collections.html.erb: adds the requirement that visibility is open.
- spec/system/front_page_spec.rb: checks that link exists and has the right query limiters.

Adjusts the Explore Our Collections link to only find Source Collections (#684).

---

app/views/catalog/_view_items_in_collection_block.html.erb
spec/system/view_collection_spec.rb

- app/views/catalog/_view_items_in_collection_block.html.erb: swaps `member_of_collections_ssim` for `source_collection_title_ssim`.
- spec/system/view_collection_spec.rb: changes link expectation.

Adjusts the View Items element to look at Source Collection Title (#693).

---

app/assets/javascripts/application.js
app/assets/javascripts/newspaper_works/ocr_search.js.erb
app/assets/stylesheets/_search_results.scss
app/assets/stylesheets/lux.scss
app/controllers/catalog_controller.rb
app/helpers/additional_catalog_helper.rb
app/helpers/newspaper_works/newspaper_works_helper_behavior.rb
app/models/search_builder.rb
app/views/catalog/_snippets_more.html.erb
config/locales/blacklight.en.yml
lib/newspaper_works/highlight_search_params.rb
spec/controllers/catalog_controller_spec.rb
spec/spec_helper.rb
spec/support/solr_documents/curate_generic_work.rb
spec/system/view_search_results_spec.rb

- app/assets/*, app/helpers/newspaper_works/newspaper_works_helper_behavior.rb, app/models/search_builder.rb, app/views/catalog/_snippets_more.html.erb, lib/newspaper_works/highlight_search_params.rb: imports code from the curate implementation.
- app/controllers/catalog_controller.rb: adds `all_text_tsimv ` field to search results and search options.
- app/helpers/additional_catalog_helper.rb: includes imported method into appropriate module.
- config/locales/blacklight.en.yml: imports localization from curate code, but changes the label verbiage per request.
- spec/*: updates expectations.
- spec/spec_helper.rb: sidesteps new webdriver Chrome behavior locally.

Adds full-text searching to Lux sites.
